services:
  - type: web
    name: iq-didactic-backend
    env: node
    region: virginia
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: DATABASE_URL
        fromDatabase:
          name: iq-didactic-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRE
        value: 7d
      - key: FRONTEND_URL
        value: https:iq-didactic-lms-demo-git-main-lottie128s-projects.vercel.app

databases:
  - name: iq-didactic-db
    databaseName: iq_didactic_db
    user: iq_didactic_db_user
    plan: free
